spring:
  application:
    name: Spring-Boot-AI-demonstration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
vectorstore:
  filename: vectorStoreFile.json