spring:
  application:
    name: Spring-Boot-AI-demonstration
  ai:
    chat:
      client:
        enabled: false
    ollama:
      chat:
        model: deepseek-r1
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
io:
  vels:
    ai:
      vectorstore:
        filename: vectorStoreFile.json
weather:
  api-key: ${WEATHER_API_KEY}
  api-url: http://api.weatherapi.com/v1